import Link from "next/link";
import { LockKeyhole, Settings, ShieldCheck, UsersRound } from "lucide-react";
import { saveProgramSettings } from "@/app/actions/program-settings";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { getLocale } from "@/lib/preferences";
import { createClient } from "@/lib/supabase/server";

export default async function ProgramSettingsPage({ params }: { params: Promise<{ slug: string }> }) {
  const [{slug},locale,supabase]=await Promise.all([params,getLocale(),createClient()]);
  const th=locale==="th";
  const {data:auth}=await supabase.auth.getUser();
  const {data:program}=await supabase.from("programs").select("id,owner_id,name,description,visibility,terms,status").eq("slug",slug).maybeSingle();
  if(!program||!auth.user) return <main className="p-6 text-sm text-slate-500">{th?"ไม่พบโปรแกรม":"Program not found."}</main>;
  const {data:staffRows}=await supabase.from("program_staff").select("user_id,role,created_at").eq("program_id",program.id).order("created_at");
  const userIds=(staffRows??[]).map(row=>row.user_id);
  const {data:profiles}=userIds.length?await supabase.from("profiles").select("id,display_name,username").in("id",userIds):{data:[]};
  const profileMap=new Map((profiles??[]).map(profile=>[profile.id,profile]));
  const currentStaff=(staffRows??[]).find(row=>row.user_id===auth.user.id);
  const canConfigure=program.owner_id===auth.user.id||["admin","manager"].includes(currentStaff?.role??"");
  return <main className="p-5 sm:p-7 lg:p-8"><div className="mx-auto max-w-4xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#087F6E]"><Settings className="size-4"/>Settings</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">{th?"ตั้งค่าโปรแกรม":"Program settings"}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{th?"ข้อมูลร้าน สิทธิ์ทีม และทางลัดด้านความปลอดภัยอยู่ในพื้นที่เดียว":"Program details, team access, and security shortcuts in one workspace."}</p>
    <section className="mt-7 rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-[#087F6E]"/><h2 className="font-semibold">{th?"ข้อมูลโปรแกรม":"Program"}</h2></div>{canConfigure?<form action={saveProgramSettings} className="mt-5 grid gap-4"><input type="hidden" name="programId" value={program.id}/><input type="hidden" name="slug" value={slug}/><label className="text-xs font-semibold text-slate-500">{th?"ชื่อโปรแกรม":"Program name"}<input required name="name" maxLength={100} defaultValue={program.name} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500">{th?"รายละเอียด":"Description"}<textarea name="description" maxLength={500} defaultValue={program.description??""} rows={3} className="mt-1 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-500">{th?"การมองเห็น":"Visibility"}<select name="visibility" defaultValue={program.visibility} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm"><option value="public">Public</option><option value="private">Private</option><option value="invite_only">Invite only</option></select></label><label className="text-xs font-semibold text-slate-500">{th?"เงื่อนไข":"Terms"}<textarea name="terms" maxLength={3000} defaultValue={program.terms??""} rows={4} className="mt-1 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2 text-sm"/></label><PendingSubmitButton pendingLabel={th?"กำลังบันทึก…":"Saving…"} className="cute-primary min-h-11 rounded-xl text-sm font-bold">{th?"บันทึกโปรแกรม":"Save program"}</PendingSubmitButton></form>:<p className="mt-4 text-sm text-slate-500">{th?"บัญชีนี้มีสิทธิ์ปฏิบัติงาน แต่ไม่มีสิทธิ์แก้การตั้งค่าระดับโปรแกรม":"This role can operate the program but cannot change program-level settings."}</p>}</section>
    <section className="mt-6 rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex items-center gap-3"><UsersRound className="size-5 text-[#087F6E]"/><div><h2 className="font-semibold">{th?"ทีมและบทบาท":"Staff & roles"}</h2><p className="text-xs text-slate-500">{th?"สิทธิ์จริงยังบังคับด้วย RLS และการตรวจฝั่งเซิร์ฟเวอร์":"Authorization remains enforced by RLS and server-side role checks."}</p></div></div><div className="mt-4 grid gap-2"><div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-white/5"><span className="grid size-9 place-items-center rounded-xl bg-[#0F2D46] text-xs font-bold text-white">O</span><div className="flex-1"><p className="text-sm font-semibold">{th?"เจ้าของโปรแกรม":"Program owner"}</p><p className="text-xs text-slate-400">owner</p></div></div>{(staffRows??[]).map(row=>{const profile=profileMap.get(row.user_id);return <div key={row.user_id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-white/5"><span className="grid size-9 place-items-center rounded-xl bg-[#E6FAF6] text-xs font-bold text-[#087F6E]">{(profile?.display_name||profile?.username||"S").slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{profile?.display_name||profile?.username||row.user_id.slice(0,8)}</p><p className="text-xs text-slate-400">{row.role}</p></div></div>})}</div></section>
    <section className="mt-6 rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center gap-3"><LockKeyhole className="size-5 text-[#087F6E]"/><div className="flex-1"><h2 className="font-semibold">{th?"ความปลอดภัยบัญชี":"Account security"}</h2><p className="mt-1 text-xs text-slate-500">{th?"รหัสผ่านและการตั้งค่าบัญชีใช้ร่วมกันทั้ง Personal และ Business":"Password and account security are shared across Personal and Business."}</p></div><Link href="/settings/security" className="cute-secondary rounded-xl px-3 py-2 text-xs font-bold">{th?"เปิด":"Open"}</Link></div></section>
  </div></main>
}
