import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { createProgram } from "@/app/actions/loyalty";

export const metadata = { title: "Create program" };

export default function NewProgramPage() {
  return <main className="mx-auto min-h-dvh max-w-xl px-5 py-6"><Link href="/home" className="inline-flex size-10 items-center justify-center rounded-full border border-zinc-200 dark:border-zinc-800"><ArrowLeft className="size-4"/></Link><div className="mt-6"><p className="text-sm font-medium text-zinc-500">Step 1–3</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Create a loyalty program</h1><p className="mt-2 text-sm leading-6 text-zinc-500">Start with points, stamps, or a hybrid program. You can add rewards and staff after creation.</p></div><form action={createProgram} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-medium">Program name<input name="name" required minLength={2} maxLength={80} className="h-12 rounded-2xl border border-zinc-200 bg-white px-4 outline-none focus:border-zinc-500 dark:border-zinc-800 dark:bg-zinc-900" placeholder="Kept Coffee"/></label><label className="grid gap-2 text-sm font-medium">Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="h-12 rounded-2xl border border-zinc-200 bg-white px-4 outline-none focus:border-zinc-500 dark:border-zinc-800 dark:bg-zinc-900" placeholder="kept-coffee"/></label><label className="grid gap-2 text-sm font-medium">Type<select name="programType" className="h-12 rounded-2xl border border-zinc-200 bg-white px-4 dark:border-zinc-800 dark:bg-zinc-900"><option value="points">Points</option><option value="stamps">Stamp Card</option><option value="hybrid">Hybrid</option></select></label><label className="grid gap-2 text-sm font-medium">Visibility<select name="visibility" className="h-12 rounded-2xl border border-zinc-200 bg-white px-4 dark:border-zinc-800 dark:bg-zinc-900"><option value="public">Public</option><option value="private">Private</option><option value="invite_only">Invite only</option></select></label><label className="grid gap-2 text-sm font-medium">Description<textarea name="description" maxLength={500} rows={4} className="rounded-2xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900" placeholder="Earn rewards every visit."/></label><button className="h-12 rounded-2xl bg-zinc-950 font-semibold text-white dark:bg-white dark:text-zinc-950">Create program</button></form></main>;
}
