"use client";

import { useEffect, useRef, useState } from "react";
import { Camera, CameraOff, CheckCircle2 } from "lucide-react";
import { acceptQrToken } from "@/app/actions/loyalty";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { normalizeQrToken } from "@/lib/share-links";

type Detector = { detect(source: HTMLVideoElement): Promise<Array<{ rawValue?: string }>> };
type DetectorCtor = new (options: { formats: string[] }) => Detector;

export function QrScanner({ initialToken="", locale }: { initialToken?: string; locale: "th"|"en" }) {
  const videoRef=useRef<HTMLVideoElement>(null);
  const streamRef=useRef<MediaStream|null>(null);
  const frameRef=useRef<number|null>(null);
  const [token,setToken]=useState(normalizeQrToken(initialToken) ?? initialToken);
  const [running,setRunning]=useState(false);
  const [message,setMessage]=useState("");
  const th=locale==="th";

  function stop(){
    if(frameRef.current) cancelAnimationFrame(frameRef.current);
    streamRef.current?.getTracks().forEach(track=>track.stop());
    streamRef.current=null;
    setRunning(false);
  }

  useEffect(()=>()=>stop(),[]);

  async function start(){
    setMessage("");
    const DetectorClass=(window as unknown as {BarcodeDetector?:DetectorCtor}).BarcodeDetector;
    if(!DetectorClass){
      setMessage(th?"เบราว์เซอร์นี้ไม่มีตัวอ่าน QR ในตัว ใช้กล้องมือถือปกติสแกน PumpPoint QR เพื่อเปิดลิงก์ หรือวางลิงก์/โทเคนด้านล่าง":"This browser has no built-in QR detector. Scan the PumpPoint QR with your normal camera to open its link, or paste the link/token below.");
      return;
    }
    try{
      const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});
      streamRef.current=stream;
      const video=videoRef.current;
      if(!video) return;
      video.srcObject=stream;
      await video.play();
      setRunning(true);
      const detector=new DetectorClass({formats:["qr_code"]});
      const scan=async()=>{
        if(!videoRef.current||!streamRef.current) return;
        try{
          const codes=await detector.detect(videoRef.current);
          const raw=codes[0]?.rawValue;
          if(raw){
            const normalized=normalizeQrToken(raw);
            if(normalized){
              setToken(normalized);
              setMessage(th?"อ่าน PumpPoint QR สำเร็จ ตรวจสอบแล้วกดยืนยัน":"PumpPoint QR detected. Review and confirm below.");
              stop();
              return;
            }
            setMessage(th?"พบ QR แต่ไม่ใช่ PumpPoint QR กรุณาสแกนโค้ดที่ร้านสร้างจากระบบ":"A QR was detected, but it is not a valid PumpPoint QR. Scan a code generated by the business workspace.");
          }
        }catch{}
        frameRef.current=requestAnimationFrame(scan);
      };
      frameRef.current=requestAnimationFrame(scan);
    }catch{
      setMessage(th?"ไม่สามารถเปิดกล้องได้ กรุณาอนุญาตสิทธิ์กล้อง หรือใช้กล้องมือถือปกติ/วางลิงก์ QR แทน":"Camera could not be opened. Allow camera access, use your normal camera, or paste the QR link instead.");
      stop();
    }
  }

  return <div className="mt-8">
    <div className="relative aspect-square overflow-hidden rounded-[32px] border border-emerald-900/20 bg-[radial-gradient(circle_at_top,#0a5d50,#062f2a_62%)] shadow-xl shadow-emerald-950/10">
      <video ref={videoRef} playsInline muted className={"h-full w-full object-cover " + (running?"block":"hidden")}/>
      {!running&&<div className="grid h-full place-items-center p-6 text-center text-white"><div><Camera className="mx-auto size-14 text-emerald-300"/><p className="mx-auto mt-4 max-w-xs text-sm leading-6 text-white/70">{th?"ใช้กล้องหลังอ่าน PumpPoint QR หรือวางลิงก์ PumpPoint QR ด้วยตนเอง":"Use the rear camera to scan a PumpPoint QR, or paste a PumpPoint QR link manually."}</p><button type="button" onClick={start} className="mt-5 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-emerald-950">{th?"เปิดกล้อง":"Open camera"}</button></div></div>}
      {running&&<button type="button" onClick={stop} className="absolute bottom-4 left-1/2 inline-flex -translate-x-1/2 items-center gap-2 rounded-full bg-black/70 px-4 py-2 text-sm font-semibold text-white backdrop-blur"><CameraOff className="size-4"/>{th?"ปิดกล้อง":"Stop"}</button>}
    </div>
    {message&&<p className="mt-3 rounded-2xl bg-zinc-100 px-4 py-3 text-sm leading-6 text-zinc-600 dark:bg-zinc-900 dark:text-zinc-300">{message}</p>}
    <form action={acceptQrToken} className="mt-5 grid gap-3">
      <label className="grid gap-2 text-sm font-medium">{th?"ลิงก์ QR หรือ Token":"QR link or token"}<input name="token" value={token} onChange={e=>setToken(e.target.value)} required maxLength={512} placeholder={th?"วาง https://pumppoint.vercel.app/q?... หรือ token":"Paste the PumpPoint QR link or token"} className="h-12 min-w-0 rounded-2xl border border-zinc-200 bg-white px-4 text-sm outline-none focus:border-emerald-500 dark:border-zinc-800 dark:bg-zinc-900"/></label>
      <PendingSubmitButton pendingLabel={th?"กำลังตรวจสอบ…":"Accepting…"} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-600 font-semibold text-white dark:bg-emerald-400 dark:text-emerald-950"><CheckCircle2 className="size-4"/>{th?"ยืนยัน QR":"Accept QR"}</PendingSubmitButton>
    </form>
  </div>;
}
