import { Award, Settings2, Stamp, WalletCards } from "lucide-react";
import { saveLoyaltySettings } from "@/app/actions/program-settings";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { getLocale } from "@/lib/preferences";
import { createClient } from "@/lib/supabase/server";

export default async function LoyaltySettingsPage({ params }: { params: Promise<{ slug: string }> }) {
  const [{ slug }, locale, supabase] = await Promise.all([params, getLocale(), createClient()]);
  const th = locale === "th";
  const { data: program } = await supabase.from("programs").select("id,name,program_type,currency_name,allow_point_transfer,point_redemption_enabled,point_tier_enabled").eq("slug", slug).maybeSingle();
  if (!program) return <main className="p-6 text-sm text-slate-500">{th ? "ไม่พบโปรแกรม" : "Program not found."}</main>;
  const { data: stampCard } = await supabase.from("stamp_cards").select("id,name,required_stamps,max_stamps_per_transaction,reset_behavior,expires_in_days,active").eq("program_id", program.id).eq("active", true).order("created_at").limit(1).maybeSingle();
  const { data: stampReward } = stampCard ? await supabase.from("rewards").select("id,name,description").eq("program_id", program.id).eq("stamp_card_id", stampCard.id).maybeSingle() : { data: null };
  const pointsCapable = program.program_type === "points" || program.program_type === "hybrid";
  const stampsCapable = program.program_type === "stamps" || program.program_type === "hybrid";

  return <main className="p-5 sm:p-7 lg:p-8"><div className="mx-auto max-w-4xl">
    <div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#087F6E]"><Settings2 className="size-4"/>Loyalty</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">{th ? "ตั้งค่าระบบ Loyalty" : "Loyalty mechanics"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">{th ? "Points และ Stamp Card เป็นคนละระบบอย่างชัดเจน ร้านเลือกได้ว่าแต้มใช้แลกรางวัล ใช้ขึ้น Tier หรือทั้งสองแบบ ส่วนบัตรสแตมป์นับจำนวนดวงเพื่อรับสิทธิพิเศษของบัตรใบนั้น" : "Points and stamp cards are separate mechanics. Choose whether points can redeem rewards, qualify for tiers, or both. Stamp cards count stamps toward a card-specific perk."}</p></div>

    <form action={saveLoyaltySettings} className="mt-7 grid gap-5">
      <input type="hidden" name="programId" value={program.id}/><input type="hidden" name="slug" value={slug}/>

      <section className={`rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6 ${pointsCapable ? "" : "opacity-70"}`}>
        <div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#E6FAF6] text-[#087F6E]"><WalletCards className="size-5"/></span><div><h2 className="font-semibold">{th ? "Points · แต้ม" : "Points"}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{pointsCapable ? (th ? "ยอดแต้มคงเหลือใช้แลกได้ตามกติกา ส่วน Lifetime Points ใช้คำนวณ Tier ได้โดยไม่ลดลงเมื่อแลก" : "Current balance can be spent on rewards. Lifetime points can separately drive tiers and do not decrease when points are redeemed.") : (th ? "โปรแกรมนี้เป็น Stamp Card เท่านั้น จึงไม่มีแต้ม" : "This is a stamp-only program, so points are disabled.")}</p></div></div>
        <div className="mt-5 grid gap-4 sm:grid-cols-2">
          <label className="text-xs font-semibold text-slate-500">{th ? "ชื่อหน่วยแต้ม" : "Point unit name"}<input required name="currencyName" defaultValue={program.currency_name} maxLength={30} disabled={!pointsCapable} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 text-sm disabled:opacity-50"/></label>
          <label className="flex min-h-11 items-center gap-3 self-end rounded-xl border border-[var(--border)] px-3 text-sm font-semibold"><input type="checkbox" name="allowPointTransfer" defaultChecked={program.allow_point_transfer} disabled={!pointsCapable}/>{th ? "อนุญาตให้สมาชิกโอนแต้ม" : "Allow member point transfers"}</label>
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <label className="rounded-2xl border border-[var(--border)] p-4"><span className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="pointRedemptionEnabled" defaultChecked={program.point_redemption_enabled} disabled={!pointsCapable}/>{th ? "ใช้แต้มแลกรางวัล" : "Use points for rewards"}</span><p className="mt-2 text-xs leading-5 text-slate-500">{th ? "หักจากยอด Points balance เมื่อสมาชิกแลก Reward" : "Deducts from the member's current point balance when redeeming a reward."}</p></label>
          <label className="rounded-2xl border border-[var(--border)] p-4"><span className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="pointTierEnabled" defaultChecked={program.point_tier_enabled} disabled={!pointsCapable}/>{th ? "ใช้แต้มสะสมขึ้น Tier" : "Use lifetime points for tiers"}</span><p className="mt-2 text-xs leading-5 text-slate-500">{th ? "Tier ดูจาก Lifetime Points ที่เคยได้รับทั้งหมด การใช้แต้มแลกรางวัลไม่ทำให้ Tier ลด" : "Tiers use lifetime points earned. Spending points does not reduce tier progress."}</p></label>
        </div>
      </section>

      {stampsCapable && <section className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#FFF4D6] text-[#B7791F]"><Stamp className="size-5"/></span><div><h2 className="font-semibold">{th ? "Stamp Card · บัตรสแตมป์" : "Stamp card"}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{th ? "สแตมป์ไม่ใช่แต้ม ไม่สามารถใช้แทน Points และไม่นับขึ้น Tier สมาชิกสะสมดวงบนบัตรนี้จนครบเพื่อรับสิทธิพิเศษที่กำหนด" : "Stamps are not points. They cannot be spent as points or used for tiers. Members fill this card to unlock its specific perk."}</p></div></div>{stampCard ? <><input type="hidden" name="stampCardId" value={stampCard.id}/><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-500">{th ? "ชื่อบัตรสแตมป์" : "Stamp card name"}<input required name="stampCardName" defaultValue={stampCard.name} maxLength={80} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500">{th ? "ครบกี่สแตมป์" : "Stamps to complete"}<input required name="requiredStamps" type="number" min="2" max="100" defaultValue={stampCard.required_stamps} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500">{th ? "สแตมป์สูงสุดต่อรายการ" : "Max stamps per transaction"}<input required name="maxStampsPerTransaction" type="number" min="1" max="100" defaultValue={stampCard.max_stamps_per_transaction} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 text-sm"/></label></div>
          <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50/70 p-4 dark:border-amber-900/60 dark:bg-amber-950/20"><div className="flex items-center gap-2"><Award className="size-4 text-amber-700"/><p className="text-sm font-semibold">{th ? "สิทธิพิเศษเมื่อครบใบ" : "Perk when the card is completed"}</p></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-500">{th ? "ชื่อสิทธิพิเศษ" : "Perk name"}<input required name="stampRewardName" defaultValue={stampReward?.name ?? "Free reward"} maxLength={100} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-white/70 px-3 text-sm dark:bg-black/10"/></label><label className="text-xs font-semibold text-slate-500">{th ? "รายละเอียด" : "Description"}<input name="stampRewardDescription" defaultValue={stampReward?.description ?? ""} maxLength={500} className="mt-1 h-11 w-full rounded-xl border border-[var(--border)] bg-white/70 px-3 text-sm dark:bg-black/10"/></label></div></div>
          <p className="mt-4 text-xs text-slate-400">{th ? `เมื่อครบ ${stampCard.required_stamps} ดวง ระบบจะทำบัตรเป็น completed เพื่อใช้สิทธิ์ แล้วเริ่มรอบใหม่ตามกติกา ${stampCard.reset_behavior}${stampCard.expires_in_days ? ` · หมดอายุใน ${stampCard.expires_in_days} วัน` : ""}` : `At ${stampCard.required_stamps} stamps the card becomes completed and can redeem its perk, then follows ${stampCard.reset_behavior}${stampCard.expires_in_days ? ` · expires in ${stampCard.expires_in_days} days` : ""}.`}</p></> : <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-100">{th ? "ยังไม่มี Stamp Card ที่เปิดใช้งาน" : "No active stamp card is configured."}</p>}</section>}

      <PendingSubmitButton pendingLabel={th ? "กำลังบันทึก…" : "Saving…"} className="cute-primary min-h-12 rounded-xl px-5 text-sm font-bold">{th ? "บันทึกการตั้งค่า Loyalty" : "Save loyalty settings"}</PendingSubmitButton>
    </form>
  </div></main>;
}
