import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { createReward } from "@/app/actions/loyalty";
import { createClient } from "@/lib/supabase/server";

export default async function RewardsAdminPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const supabase = await createClient();
  const { data: program } = await supabase.from("programs").select("id,name").eq("slug", slug).single();
  const { data: rewards } = program ? await supabase.from("rewards").select("id,name,reward_type,points_required,stamps_required,stock,active").eq("program_id", program.id).order("created_at", { ascending: false }) : { data: [] };
  if (!program) return <main className="p-6">Program not found.</main>;
  return <main className="mx-auto min-h-dvh max-w-xl px-5 py-6"><Link href={`/programs/${slug}/manage`} className="inline-flex size-10 items-center justify-center rounded-full border border-zinc-200 dark:border-zinc-800"><ArrowLeft className="size-4"/></Link><h1 className="mt-7 text-3xl font-semibold tracking-[-0.04em]">Rewards</h1><form action={createReward} className="mt-6 grid gap-3 rounded-[24px] border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"><input type="hidden" name="programId" value={program.id}/><input type="hidden" name="slug" value={slug}/><input name="name" required maxLength={100} placeholder="Free latte" className="h-12 rounded-xl border border-zinc-200 bg-transparent px-4 dark:border-zinc-800"/><textarea name="description" maxLength={500} placeholder="Reward description" className="rounded-xl border border-zinc-200 bg-transparent p-4 dark:border-zinc-800"/><div className="grid grid-cols-2 gap-3"><select name="rewardType" className="h-12 rounded-xl border border-zinc-200 bg-transparent px-3 dark:border-zinc-800"><option value="points">Points</option><option value="stamps">Stamps</option><option value="free">Free</option><option value="manual">Manual</option></select><input name="cost" type="number" min="1" placeholder="Cost" className="h-12 rounded-xl border border-zinc-200 bg-transparent px-4 dark:border-zinc-800"/></div><input name="stock" type="number" min="0" placeholder="Stock (blank = unlimited)" className="h-12 rounded-xl border border-zinc-200 bg-transparent px-4 dark:border-zinc-800"/><button className="h-12 rounded-xl bg-zinc-950 font-semibold text-white dark:bg-white dark:text-zinc-950">Add reward</button></form><div className="mt-6 grid gap-3">{(rewards ?? []).map((reward)=><div key={reward.id} className="rounded-[22px] border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{reward.name}</p><p className="mt-1 text-sm text-zinc-500">{reward.reward_type} · {reward.points_required ?? reward.stamps_required ?? "manual"}</p></div><span className="text-xs text-zinc-500">{reward.stock == null ? "Unlimited" : `${reward.stock} left`}</span></div></div>)}</div></main>;
}
